# Generated by Django 5.2.2 on 2025-09-01 09:24

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL')),
                ('subtitle', models.CharField(blank=True, max_length=400, verbose_name='Краткое описание')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='articles/covers/', verbose_name='Обложка/превью')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст статьи')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pub', 'Опубликована')], default='draft', max_length=10, verbose_name='Статус')),
                ('published_at', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
