# Generated by Django 5.2.2 on 2025-09-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_part', '0020_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryChar',
            fields=[
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_part.category',),
        ),
        migrations.CreateModel(
            name='ColorChar',
            fields=[
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_part.color',),
        ),
        migrations.CreateModel(
            name='EmptinessChar',
            fields=[
            ],
            options={
                'verbose_name': 'Пустотность',
                'verbose_name_plural': 'Пустотность',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_part.emptiness',),
        ),
        migrations.CreateModel(
            name='FormatChar',
            fields=[
            ],
            options={
                'verbose_name': 'Формат',
                'verbose_name_plural': 'Форматы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_part.format',),
        ),
        migrations.CreateModel(
            name='FrosenDefenderChar',
            fields=[
            ],
            options={
                'verbose_name': 'Марка прочности',
                'verbose_name_plural': 'Марка прочности',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_part.frosendefender',),
        ),
        migrations.CreateModel(
            name='GalleryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Фото товара',
                'verbose_name_plural': 'Фото товара',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_part.gallery',),
        ),
        migrations.CreateModel(
            name='ManufactorChar',
            fields=[
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_part.manufactor',),
        ),
        migrations.CreateModel(
            name='ProductTypeChar',
            fields=[
            ],
            options={
                'verbose_name': 'Тип товара',
                'verbose_name_plural': 'Типы товаров',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_part.producttype',),
        ),
        migrations.CreateModel(
            name='StrengthGradeChar',
            fields=[
            ],
            options={
                'verbose_name': 'Морозостойкость',
                'verbose_name_plural': 'Морозостойкость',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_part.strengthgrade',),
        ),
        migrations.CreateModel(
            name='TypeMaterialChar',
            fields=[
            ],
            options={
                'verbose_name': 'Вид материала',
                'verbose_name_plural': 'Виды материалов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_part.typematerial',),
        ),
        migrations.CreateModel(
            name='WaterResistanceChar',
            fields=[
            ],
            options={
                'verbose_name': 'Водопоглощение',
                'verbose_name_plural': 'Водопоглощение',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_part.waterresistance',),
        ),
    ]
