# Generated by Django 5.2.2 on 2025-10-23 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characteristics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frosendefenderchar',
            options={'verbose_name': 'Морозостойкость', 'verbose_name_plural': 'Морозостойкость'},
        ),
        migrations.AlterModelOptions(
            name='strengthgradechar',
            options={'verbose_name': 'Марка прочности', 'verbose_name_plural': 'Марка прочности'},
        ),
    ]
