# Generated by Django 5.2.2 on 2025-06-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0002_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='link_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
