# Generated by Django 5.2.2 on 2025-06-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0003_category_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='card_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
