# Generated by Django 5.2.2 on 2025-06-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0004_alter_product_card_image_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
