# Generated by Django 5.2.2 on 2025-06-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0005_alter_product_card_image_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
