# Generated by Django 5.2.2 on 2025-06-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0006_category_card_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
