# Generated by Django 5.2.2 on 2025-06-25 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0008_color_emptiness_format_frosendefender_manufactor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='strength_grade',
        ),
        migrations.AddField(
            model_name='product',
            name='strength_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.strengthgrade'),
        ),
    ]
