# Generated by Django 5.2.1 on 2025-08-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0010_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link_name', models.CharField(max_length=100, null=True)),
                ('card_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='frosendefender',
            options={'verbose_name': 'Марка прочности', 'verbose_name_plural': 'Марка прочности'},
        ),
        migrations.AlterModelOptions(
            name='strengthgrade',
            options={'verbose_name': 'Морозостойкость', 'verbose_name_plural': 'Морозостойкость'},
        ),
    ]
