# Generated by Django 5.2.1 on 2025-07-01 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0010_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufactor',
            new_name='Manufacturer',
        ),
        migrations.AlterField(
            model_name='product',
            name='emptiness',
            field=models.ManyToManyField(blank=True, to='shop_part.emptiness'),
        ),
        migrations.AlterField(
            model_name='product',
            name='formats',
            field=models.ManyToManyField(blank=True, to='shop_part.format'),
        ),
    ]
