# Generated by Django 5.2.1 on 2025-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0011_rename_manufactor_manufacturer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufacturer',
            new_name='Manufactor',
        ),
        migrations.AlterField(
            model_name='product',
            name='emptiness',
            field=models.ManyToManyField(to='shop_part.emptiness'),
        ),
        migrations.AlterField(
            model_name='product',
            name='formats',
            field=models.ManyToManyField(to='shop_part.format'),
        ),
    ]
