# Generated by Django 5.2.2 on 2025-08-01 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0012_image_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigGalery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Позиция в списке', verbose_name='позиция в списке')),
                ('name', models.CharField(help_text='Имя объекта', max_length=100, verbose_name='имя(текст на картинке)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='текст при наведении на точку')),
                ('card_image', models.ImageField(blank=True, help_text='Изображение в галерее', null=True, upload_to='', verbose_name='Фото отобрадаеыя при открытии')),
            ],
            options={
                'verbose_name': 'Галерея объектов',
                'verbose_name_plural': 'Галерея объектов',
            },
        ),
        migrations.CreateModel(
            name='SmallGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото объекта')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop_part.biggalery')),
            ],
        ),
        migrations.DeleteModel(
            name='image',
        ),
        migrations.DeleteModel(
            name='items',
        ),
    ]
