# Generated by Django 5.2.2 on 2025-08-01 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0013_biggalery_smallgallery_delete_image_delete_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biggalery',
            name='description',
        ),
        migrations.AddField(
            model_name='biggalery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.product', verbose_name='Объект отображаемый при наведении на точку'),
        ),
    ]
