# Generated by Django 5.2.2 on 2025-08-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0014_remove_biggalery_description_biggalery_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smallgallery',
            options={'verbose_name': 'Фото объекта при открытии', 'verbose_name_plural': 'Фото объекта при открытии'},
        ),
        migrations.AlterField(
            model_name='biggalery',
            name='card_image',
            field=models.ImageField(blank=True, help_text='Изображение в галерее', null=True, upload_to='', verbose_name='Фото карточки объекта в общем списке'),
        ),
    ]
