# Generated by Django 5.2.2 on 2025-08-01 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0015_alter_smallgallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biggalery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.product', verbose_name='Товар отображаемый при наведении на точку'),
        ),
    ]
