# Generated by Django 5.2.2 on 2025-09-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0017_contactrequest_delete_galery'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filters_enabled',
            field=models.JSONField(blank=True, default=list, help_text='Список ключей фильтров из FilterKey.*'),
        ),
    ]
