# Generated by Django 5.2.2 on 2025-09-14 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0018_category_filters_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='emptiness',
            field=models.ManyToManyField(blank=True, null=True, to='shop_part.emptiness'),
        ),
        migrations.AlterField(
            model_name='product',
            name='formats',
            field=models.ManyToManyField(blank=True, null=True, to='shop_part.format'),
        ),
        migrations.AlterField(
            model_name='product',
            name='frosen_defend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.frosendefender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.producttype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='strength_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.strengthgrade'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop_part.typematerial'),
        ),
        migrations.AlterField(
            model_name='product',
            name='water_resistance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.waterresistance'),
        ),
    ]
