# Generated by Django 5.2.2 on 2025-09-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0019_alter_product_color_alter_product_emptiness_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='emptiness',
            options={'verbose_name': 'Пустотность', 'verbose_name_plural': 'Пустотность'},
        ),
        migrations.AlterModelOptions(
            name='format',
            options={'verbose_name': 'Формат', 'verbose_name_plural': 'Форматы'},
        ),
        migrations.AlterModelOptions(
            name='manufactor',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'verbose_name': 'Тип товара', 'verbose_name_plural': 'Типы товаров'},
        ),
        migrations.AlterModelOptions(
            name='typematerial',
            options={'verbose_name': 'Вид материала', 'verbose_name_plural': 'Виды материалов'},
        ),
        migrations.AlterModelOptions(
            name='waterresistance',
            options={'verbose_name': 'Водопоглощение', 'verbose_name_plural': 'Водопоглощение'},
        ),
        migrations.AddField(
            model_name='biggalery',
            name='our_supplies',
            field=models.BooleanField(blank=True, null=True, verbose_name='Наши поставки'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='emptiness',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Пустотность'),
        ),
        migrations.AlterField(
            model_name='format',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='frosendefender',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Марка прочности'),
        ),
        migrations.AlterField(
            model_name='manufactor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фото карточки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='emptiness',
            field=models.ManyToManyField(blank=True, to='shop_part.emptiness', verbose_name='Пустотность'),
        ),
        migrations.AlterField(
            model_name='product',
            name='formats',
            field=models.ManyToManyField(blank=True, to='shop_part.format', verbose_name='Форматы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='frosen_defend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.frosendefender', verbose_name='Марка прочности'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.manufactor', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.producttype', verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='strength_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.strengthgrade', verbose_name='Морозостойкость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop_part.typematerial', verbose_name='Вид материала'),
        ),
        migrations.AlterField(
            model_name='product',
            name='water_resistance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.waterresistance', verbose_name='Водопоглощение'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Тип товара'),
        ),
        migrations.AlterField(
            model_name='strengthgrade',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Морозостойкость'),
        ),
        migrations.AlterField(
            model_name='waterresistance',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Водопоглощение'),
        ),
    ]
