# Generated by Django 5.2.2 on 2025-09-28 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0020_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_price',
            field=models.TextField(blank=True, null=True, verbose_name='Прайс лист товара'),
        ),
    ]
