# Generated by Django 5.2.2 on 2025-09-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0022_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Телефон для контактов'),
        ),
    ]
