# Generated by Django 5.2.2 on 2025-10-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0023_sitesettings_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='promo_tag',
            field=models.CharField(blank=True, choices=[('favorite', 'Фаворит'), ('sale', 'Акция'), ('new', 'Новинка')], help_text='Отображается как бейдж на карточке: Фаворит / Акция / Новинка', max_length=16, null=True, verbose_name='Метка товара'),
        ),
    ]
