# Generated by Django 5.2.2 on 2025-10-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0024_product_promo_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='similar_products_manual',
            field=models.ManyToManyField(blank=True, related_name='manually_recommended_for', to='shop_part.product', verbose_name='Похожие товары (ручной выбор)'),
        ),
    ]
