# Generated by Django 5.2.2 on 2025-10-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0025_product_similar_products_manual'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-priority', '-id'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='priority',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Приоритет сортировки (чем больше — выше)'),
        ),
    ]
