# Generated by Django 5.2.2 on 2025-10-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0026_alter_product_options_product_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок (большой)')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='Подзаголовок (средний)')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Картинка')),
                ('cta_url', models.URLField(verbose_name='Ссылка для кнопки «Узнать подробнее»')),
            ],
        ),
    ]
