# Generated by Django 5.2.2 on 2025-10-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0027_bannerslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerslide',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Картинка (мобильная версия)'),
        ),
    ]
