# Generated by Django 5.2.2 on 2025-10-23 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0028_bannerslide_image_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frosendefender',
            options={'verbose_name': 'Морозостойкость', 'verbose_name_plural': 'Морозостойкость'},
        ),
        migrations.AlterModelOptions(
            name='strengthgrade',
            options={'verbose_name': 'Марка прочности', 'verbose_name_plural': 'Марка прочности'},
        ),
        migrations.AlterField(
            model_name='bannerslide',
            name='image',
            field=models.ImageField(upload_to='hero_slides/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='bannerslide',
            name='image_mobile',
            field=models.ImageField(blank=True, null=True, upload_to='hero_slides/', verbose_name='Картинка (мобильная версия)'),
        ),
        migrations.AlterField(
            model_name='frosendefender',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Морозостойкость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='frosen_defend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.frosendefender', verbose_name='Морозостойкость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='strength_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop_part.strengthgrade', verbose_name='Марка прочности'),
        ),
        migrations.AlterField(
            model_name='strengthgrade',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Марка прочности'),
        ),
    ]
