# Generated by Django 5.2.2 on 2025-11-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0029_alter_frosendefender_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
    ]
