# Generated by Django 5.2.2 on 2025-11-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0030_alter_contactrequest_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия'),
        ),
    ]
