# Generated by Django 5.2.2 on 2026-04-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_part', '0031_alter_contactrequest_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerslide',
            name='background_theme',
            field=models.CharField(choices=[('brown', 'Коричневый'), ('light', 'Светлый')], default='brown', max_length=10, verbose_name='Цвет фона баннера'),
        ),
        migrations.AddField(
            model_name='bannerslide',
            name='image_only',
            field=models.BooleanField(default=False, help_text='Если включено, баннер отображается только как картинка без текста и кнопок.', verbose_name='Только картинка'),
        ),
        migrations.AlterField(
            model_name='bannerslide',
            name='cta_url',
            field=models.URLField(blank=True, verbose_name='Ссылка для кнопки «Узнать подробнее»'),
        ),
        migrations.AlterField(
            model_name='bannerslide',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Заголовок (большой)'),
        ),
    ]
