# Generated by Django 5.2.2 on 2026-09-15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_part", "0032_bannerslide_background_theme_bannerslide_image_only_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Актуальная цена"),
        ),
        migrations.AddField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Заполняется только для скидки и должна быть выше актуальной цены.", max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Старая цена"),
        ),
        migrations.AddField(
            model_name="product",
            name="currency",
            field=models.CharField(choices=[("RUB", "Российский рубль (RUB)"), ("USD", "Доллар США (USD)"), ("UAH", "Украинская гривна (UAH)"), ("KZT", "Казахстанский тенге (KZT)")], default="RUB", max_length=3, verbose_name="Валюта"),
        ),
        migrations.AddField(model_name="product", name="feed_enabled", field=models.BooleanField(default=True, verbose_name="Включать в Яндекс-фид")),
        migrations.AddField(model_name="product", name="feed_id2", field=models.CharField(blank=True, max_length=100, verbose_name="ID2 для Яндекс-фида")),
        migrations.AddField(model_name="product", name="custom_label_0", field=models.CharField(blank=True, max_length=175, verbose_name="custom_label_0")),
        migrations.AddField(model_name="product", name="custom_label_1", field=models.CharField(blank=True, max_length=175, verbose_name="custom_label_1")),
        migrations.AddField(model_name="product", name="custom_label_2", field=models.CharField(blank=True, max_length=175, verbose_name="custom_label_2")),
        migrations.AddField(model_name="product", name="custom_label_3", field=models.CharField(blank=True, max_length=175, verbose_name="custom_label_3")),
        migrations.AddField(model_name="product", name="custom_label_4", field=models.CharField(blank=True, max_length=175, verbose_name="custom_label_4")),
        migrations.AddField(model_name="product", name="custom_score", field=models.PositiveIntegerField(blank=True, null=True, verbose_name="custom_score")),
    ]
