# Generated by Django 5.2.2 on 2025-09-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop_part', '0020_alter_category_options_alter_color_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigGaleryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Галерея объектов',
                'verbose_name_plural': 'Галерея объектов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_part.biggalery',),
        ),
        migrations.CreateModel(
            name='SmallGalleryProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Фото объекта при открытии',
                'verbose_name_plural': 'Фото объекта при открытии',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop_part.smallgallery',),
        ),
    ]
