"""
Django settings for FasadSiteDjango project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import json

from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-osykeufd%)o^tok%1c^dmw_bbgf79-76js009c$_$#=gqim3v7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['modernfasad.ru', '164.215.97.73', '127.0.0.1', 'localhost', '*']

# Application definition

INSTALLED_APPS = [
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop_part',
    "ckeditor",
    "ckeditor_uploader",
    "articles",
    'characteristics.apps.CharacteristicsConfig',  # новое
    'gallery.apps.GalleryConfig',
    'import_export'
]
CKEDITOR_CONFIGS = {
    "article": {
        "height": 400,
        "toolbar_Basic": [],
        "toolbar": "Custom",
        "toolbar_Custom": [
            {"name": "styles", "items": ["Format", "Styles"]},
            {"name": "basicstyles", "items": ["Bold", "Italic", "Underline", "Strike", "-", "RemoveFormat"]},
            {"name": "paragraph",
             "items": ["NumberedList", "BulletedList", "-", "Outdent", "Indent", "-", "JustifyLeft", "JustifyCenter",
                       "JustifyRight", "JustifyBlock"]},
            {"name": "links", "items": ["Link", "Unlink"]},
            {"name": "insert", "items": ["Image", "Table", "HorizontalRule"]},
            {"name": "clipboard", "items": ["Undo", "Redo"]},
            {"name": "document", "items": ["Source"]},
        ],
        # позволяем классы/стили, чтобы применять колонки и т.п.
        "extraAllowedContent": "*(*){*};*[*]",
        "removeDialogTabs": "image:advanced;link:advanced",
        "autoGrow_onStartup": True,
        "extraPlugins": ",".join(["autogrow", "justify", "uploadimage", "div"]),
        # выпадающий список «Styles» (не требует знания HTML со стороны редактора)
        "stylesSet": [
            {"name": "2 колонки", "element": "div", "attributes": {"class": "columns-2"}},
            {"name": "3 колонки", "element": "div", "attributes": {"class": "columns-3"}},
            {"name": "Заметка", "element": "div", "attributes": {"class": "note"}},
            {"name": "Цитата", "element": "blockquote", "attributes": {"class": "quote"}},
            {"name": "Мелкий подпункт", "element": "p", "attributes": {"class": "small"}}
        ],
    }
}

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin-allow-popups"

MIDDLEWARE = [
    "FasadSiteDjango.middleware.metrika_headers.DisableCoopForMetrikaMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'FasadSiteDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "shop_part.context_processors.site_settings",
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": "db.sqlite3"}}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = [BASE_DIR / "static_dev"]

# STORAGES = {
#     "staticfiles": {
#         "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
#     },
# }
MEDIA_URL = '/uploads/'
MEDIA_ROOT = BASE_DIR / 'uploads'
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
TEMPLATES[0]["OPTIONS"]["context_processors"] += [
    "shop_part.context_processors.faq_questions",
]
